### PR TITLE
filter nulls

### PR DESCRIPTION
**Pull request by bendavies**
Fixes:
https://github.com/SyliusLabs/AssociationHydrator/pull/3#issuecomment-456063361

### CODE REVIEW

**Comment by bendavies** [comment]
@pamil any chance of a review?

**Comment by maximehuran** [comment]
ping @pjedrzejewski ?

**Comment by antoinemeeus** [comment]
Any chance for review ?

**Comment by pptasinski-mytheresa** [comment]
Yeah - would be great to merge it :100:

**Comment by Michal-Szczepaniak** [comment]
I've asked sylius people about updating this package and from the info I've got they got it noted but they're busy currently so gotta wait a bit unfortunately

**Review by Rafikooo — APPROVED** [review]

**Review by pptasinski-mytheresa — APPROVED** [review]

**Pull request merged**
